openapi: 3.0.3
info:
  title: Quipt - OpenAPI 3.0
  description: >-
    The [Vendor API](#tag-vendor-api) is a robust and adaptable suite of tools designed to
    seamlessly integrate with your existing systems, enabling efficient and
    scalable sales management. By automating manual tasks, streamlining
    workflows, and providing real-time data insights, the API empowers
    businesses to:
      - Enhance operational efficiency
      - Reduce costs and operational overhead
      - Drive sales growth and market reach
      - Offer an improved customer experience
    
    The [Channel API](#tag-channel-api) empowers organizations to automate their purchasing
    functions, transforming their procurement landscape for enhanced efficiency,
    cost savings, and control. By automating manual tasks, streamlining
    workflows, and providing real-time data insights, the API empowers
    businesses to:
      - Search and compare products from diverse merchants through a centralized
    platform.
      - Access real-time inventory data and pricing information.
      - Streamline product selection and requisition processes.
      - Create and submit purchase orders electronically to multiple retailers.
      - Track order status, delivery updates, and invoices in real-time.
    
    The [Carrier API](#tag-Carrier_API) is a set of endpoints to get the available carriers and carrier methods that are used as part of the order workflows. They are used as part of the order and shipment endpoints. 
    
    
    The [Taxonomy API](#tag-Taxonomy_API) is a set of endpoints to get the available carriers and carrier methods that are used as part of the order workflows. They are used as part of the order and shipment endpoints. 
    
    
    The [Notifcation API](#tag-Notification_API) is a set of endpoints to get application events. Important the user you are using to monitor the events must be subscribed using the [web application](https://app.getquipt.com/#/Settings/MySettings). 
    
    
    Some useful links:
      - [OAuth 1.0a Specification](http://tools.ietf.org/html/rfc5849)


    Samples to call protected resources:
      - [PHP]()
      - [BASH script]()
      - [C#]()
  termsOfService: https://getquipt.com/terms-of-service/
  version: 1.0.0
servers:
  - url: https://api.getquipt.com/v2
tags:
  - name: Vendor API - Inventory
    description: Perform merchant workflows.
  - name: Vendor API - Orders
    description: Perform merchant workflows.
  - name: Vendor API - Shipments
    description: Perform merchant workflows.
  - name: Vendor API - Requests
    description: Perform merchant workflows.
  - name: Channel API - Virtual Inventory
    description: Perform retailer workflows.
  - name: Channel API - Orders
    description: Perform retailer workflows.
  - name: Channel API - Requests
    description: Perform retailer workflows.
  - name: Catalog API
    description: Search product catalog.
  - name: Notification API
    description: Get notifications/events.
  - name: Carrier API
    description: |
      Get carrier details.  
      For the full list of carriers and shipping methods, see the external docs below.
  - name: Taxonomy API
    description: >-
      Categories are arranged in a tree structure, where:<br/>
      - Each category has a unique id.<br/>
      - A category can have multiple child categories.<br/>
      - A category must have IsLeaf: true to have a product assigned to it.
      - Any category may have Attributes associated, but refer to categories with IsLeaf: true to see those required for a category.
paths:
  /inventory/physical:
    post:
      tags:
        - Vendor API - Inventory
      summary: Add or update items.
      description: Add or update items.
      operationId: addUpdateInventoryItems
      security:
        - quipt_auth:
            - write:inventory
  /inventory/physical/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getAddUpdateInventoryItemsReport
      security:
        - quipt_auth:
            - read:inventory  
  /inventory/physical/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get physical inventory items.
      description: Get a paged list of inventory items based on search parameters.
      operationId: getPhysicalInventory
      security:
        - quipt_auth:
            - read:inventory
  /inventory/physical/id/{id}:
    get:
      tags:
        - Vendor API - Inventory
      summary: Get physical inventory item by id.
      description: Get physical inventory item by id.
      operationId: getPhysicalInventoryById
      security:
        - quipt_auth:
            - read:inventory
  /orders/fulfillment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get orders.
      description: Get orders by page.
      operationId: getFulfillmentOrders
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/id/{id}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get order by id.
      description: Get order by id.
      operationId: getFulfillmentOrdersById
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/po/{channelIdOrCode}/{poNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get order by purchase order number.
      description: Get order by purchase order number.
      operationId: getFulfillmentOrdersByPO
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/channel/{channelIdOrCode}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get orders by channel.
      description: Get orders by channel.
      operationId: getFulfillmentOrdersByChannel
      security:
        - quipt_auth:
            - read:orders
  /orders/fulfillment/acknowledge:
    post:
      tags:
        - Vendor API - Orders
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: ackFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders
  /orders/fulfillment/ship:
    post:
      tags:
        - Vendor API - Orders
      summary: Ship orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: shipFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders   
  /orders/fulfillment/invoice:
    post:
      tags:
        - Vendor API - Orders
      summary: Ship orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: invoiceFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders
  /orders/fulfillment/archive:
    post:
      tags:
        - Vendor API - Orders
      summary: Archive orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archiveFulfillmentOrders
      security:
        - quipt_auth:
            - write:orders     
  /orders/fulfillment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Orders
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateFulfillmentOrdersReport
      security:
        - quipt_auth:
            - read:orders  
  /orders/shipment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get orders.
      description: Get orders by page.
      operationId: getFulfillmentShipments
      security:
        - quipt_auth:
            - read:shipments
  /orders/shipment/id/{id}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get shipment by id.
      description: Get shipment by id.
      operationId: getFulfillmentShipmentsById
      security:
        - quipt_auth:
            - read:orders
  /orders/shipment/acknowledge:
    post:
      tags:
        - Vendor API - Shipments
      summary: Update virtual items.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: ackFulfillmentShipments
      security:
        - quipt_auth:
            - write:shipments
  /orders/shipment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Shipments
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateFulfillmentShipmentsReport
      security:
        - quipt_auth:
            - read:shipments
  /requests/fulfillment/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get orders.
      description: Get orders by page.
      operationId: getFulfillmentRequests
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/{channelIdOrCode}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get orders.
      description: Get orders by page.
      operationId: getFulfillmentRequestsByChannel
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/id/{id}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get order by id.
      description: Get order by id.
      operationId: getFulfillmentRequestsById
      security:
        - quipt_auth:
            - read:requests
  /requests/fulfillment/acknowledge:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: ackFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/create:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: addFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/returnupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateFulfillmentRequestsReturn
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/missingaccessoryupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateFulfillmentRequestsMissingAccessory
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/lostshipmentupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateFulfillmentRequestsLostShipment
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/interceptupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateFulfillmentRequestsIntercept
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/creditupdate:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateFulfillmentRequestsCredit
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/cancel:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: cancelFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/archive:
    post:
      tags:
        - Vendor API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archiveFulfillmentRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/fulfillment/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Vendor API - Requests
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateFulfillmentRequestsReport
      security:
        - quipt_auth:
            - read:shipments
  /inventory/virtual/acknowledge:
    post:
      tags:
        - Channel API - Virtual Inventory
      summary: Update virtual items.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateVirtualInventoryItems
      security:
        - quipt_auth:
            - write:feeds
  /inventory/virtual/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateVirtualInventoryItemsReport
      security:
        - quipt_auth:
            - read:feeds 
  /inventory/virtual/{merchantId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get virtual inventory items.
      description: Get a paged list of virtual inventory items based on search parameters.
      operationId: getVirtualInventory
      security:
        - quipt_auth:
            - read:feeds
  /inventory/virtual/id/{id}:
    get:
      tags:
        - Channel API - Virtual Inventory
      summary: Get virtual inventory item by id.
      description: Get virtual inventory item by id.
      operationId: getVirtualInventoryById
      security:
        - quipt_auth:
            - read:feeds
  /orders/purchase/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get orders.
      description: Get orders by page.
      operationId: getPurchaseOrders
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/id/{id}:
    get:
      tags:
        - Channel API - Orders
      summary: Get order by id.
      description: Get order by id.
      operationId: getPurchaseOrdersById
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/ordernumber/{poNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get order by purchase order number.
      description: Get order by purchase order number.
      operationId: getPurchaseOrdersByPO
      security:
        - quipt_auth:
            - read:orders
  /orders/purchase/create:
    post:
      tags:
        - Channel API - Orders
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: addPurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/acknowledge:
    post:
      tags:
        - Channel API - Orders
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: ackPurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/cancel:
    post:
      tags:
        - Channel API - Orders
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: cancelPurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/archive:
    post:
      tags:
        - Channel API - Orders
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archivePurchaseOrders
      security:
        - quipt_auth:
            - write:requests
  /orders/purchase/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Orders
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdatePurchaseOrdersReport
      security:
        - quipt_auth:
            - read:shipments
  /requests/purchase/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get orders.
      description: Get orders by page.
      operationId: getPurchaseRequests
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/ordernumber/{poNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get orders.
      description: Get orders by page.
      operationId: getPurchaseRequestsByPO
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/referencenumber/{refNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get orders.
      description: Get orders by page.
      operationId: getPurchaseRequestsByRefNumber
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/id/{id}:
    get:
      tags:
        - Channel API - Requests
      summary: Get order by id.
      description: Get order by id.
      operationId: getPurchaseRequestsById
      security:
        - quipt_auth:
            - read:requests
  /requests/purchase/acknowledge:
    post:
      tags:
        - Channel API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: ackPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/create:
    post:
      tags:
        - Channel API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: addPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/cancel:
    post:
      tags:
        - Channel API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: cancelPurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/archive:
    post:
      tags:
        - Channel API - Requests
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archivePurchaseRequests
      security:
        - quipt_auth:
            - write:requests
  /requests/purchase/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Channel API - Requests
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdatePurchaseRequestsReport
      security:
        - quipt_auth:
            - read:requests
  /notifications/{pageSize}/{pageNumber}:
    get:
      tags:
        - Notification API
      summary: Get orders.
      description: Get orders by page.
      operationId: getNotifications
      security:
        - quipt_auth:
            - read:requests
  /notifications/update:
    post:
      tags:
        - Notification API
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: updateNotifications
      security:
        - quipt_auth:
            - write:requests
  /notifications/archive:
    post:
      tags:
        - Notification API
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archiveNotifications
      security:
        - quipt_auth:
            - write:requests
  /notifications/report/{reportId}/{pageSize}/{pageNumber}:
    get:
      tags:
        - Notification API
      summary: Get job report details by ReportId.  
      description: Get job report details by ReportId.
      operationId: getUpdateNotificationsReport
      security:
        - quipt_auth:
            - read:requests
  /notifications/{notificationId}/archive:
    post:
      tags:
        - Notification API
      summary: Acknowledge orders.
      description: >-
          Let the vendor know you have listed or have an issue with the item they are selling.<br/>
          If listed forsale send the following properties within the request. 
            - ARP: { Optional, Current sale price. }<br/> 
            - CatalogStatus: 40<br/>
            - MapId: { Optional, Your internal identifier. }<br/>
            - MapURL: { Optional, The link to the item on your site. }<br/>
            
          If there is an issue send the following properties within the request.
             - CatalogStatus: 30<br/>
             - Messages: { The reason the item is not listed. }<br/>
      operationId: archiveNotificationsById
      security:
        - quipt_auth:
            - write:requests
  /catalog/{pageSize}/{pageNumber}:
    get:
      tags:
        - Catalog API
      summary: Get orders.
      description: Get orders by page.
      operationId: getCatalogItems
      security:
        - quipt_auth:
            - read:requests
  /carriers:
    get:
      tags:
        - Carrier API
      summary: Get supported carriers.
      description: Get supported carriers.
      operationId: getCarriers
  /carriers/methods:
    get:
      tags:
        - Carrier API
      summary: Get supported carrier methods.
      description: Get supported carrier methods.
      operationId: getCarrierMethods
  /carriers/{carrierCode}/methods:
    get:
      tags:
        - Carrier API
      summary: Get supported carrier methods by carrier.
      description: Get supported carrier methods by carrier.
      operationId: getCarrierMethodsByCarrierCode
  /categories:
    get:
      tags:
        - Taxonomy API
      summary: Get root categories.
      description: >-
        Get top level categories defined within Quipt.
      operationId: getRootCategories
  /categories/{categoryId}:
    get:
      tags:
        - Taxonomy API
      summary:  Get children categories.
      description: >-
        Get children categories. Used to traverse the category tree. If the intention is to list against the selected category ensure IsLeaf is true.
      operationId: getCategoriesByParentId
  /categories/search:        
    get:
      tags:
        - Taxonomy API
      summary: Get the categories that best match the provided keywords.  
      description: >-
        Get the categories that best match the provided keywords. One thing to keep in mind is we will perform 2 searches.
          1. Catalog search to identify relevant categories.
          2. Category tree search to identify categories that match provided keywords.
        Also, keep in mind returned categories may not have IsLeaf as true, so you will need to use getCategoriesbyParentId to identify a leaf category.
      operationId: getCategoriesByKeywords
  /categories/{categoryId}/attributes:
    get:
      tags:
        - Taxonomy API
      summary: Get the attributes associated to the category. 
      description: >-
        Get the attributes associated to the category. If the intention is to list against the selected category ensure IsLeaf is true.
      operationId: getAttributesByCategoryId
components:
  securitySchemes:
    quipt_auth:
      type: apiKey
      in: header
      name: Authorization
      description: >
        OAuth 1.0 authentication requires the following steps:

        1. Obtain a consumer key and secret from the API provider.

        2. Generate an OAuth signature using HMAC-SHA1 or another supported
        method.

        3. Include the `Authorization` header in your request with the OAuth 1.0
        credentials.

        Example:

        ```

        Authorization: OAuth oauth_consumer_key="key", oauth_token="token",
        oauth_signature_method="HMAC-SHA1", oauth_timestamp="timestamp",
        oauth_nonce="nonce", oauth_version="1.0", oauth_signature="signature"

        ```
